core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact', views.contact, name='contact'),
    path('registro', views.create_user),
    path('results', views.results, name='results'),
    path('projects', views.projects, name='projects'),
]

random_word/urls.py
from django.urls import path
from . import views

app_name = 'random_word'

urlpatterns = [
    path('', views.index, name='home'),
    path('random', views.random, name='random'),
    path('reset', views.reset, name='reset'),
]

core/models.py
from django.db import models

# Create your models here.

random_word/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, redirect, reverse

# Create your views here.
def home(request):    
    return render(request, 'core/index.html')


def contact(request):
    request.session["errores"] = []
    request.session["email"] = ""
    request.session["nombre"] = ""
    request.session["ciudad"] = ""
    return render(request, 'core/contact.html')
    

def create_user(request):    
    if request.method == 'GET':
        return render(request, 'core/create_user.html')
    elif request.method == 'POST':
        errores = []
        email = request.POST["email"].strip()
        nombre = request.POST["nombre"].strip()
        ciudad = request.POST["ciudad"].strip()

        if len(email) == 0:
            errores.append("Please enter your email address")
        if len(nombre) == 0:
            errores.append("Please enter your name")
        if len(ciudad) == 0:
            errores.append("Please enter your native city")  

        if len(errores) == 0:                    
            request.session["email"] = email
            request.session["nombre"] = nombre
            request.session["ciudad"] = ciudad
            if 'contador' in request.session:
                request.session['contador'] += 1
            else:
                request.session['contador'] = 1
        else:
            request.session["errores"] = errores
        
        return redirect("/results")
        

def results(request):
    return render(request, 'core/results.html')

def projects(request):
    return render(request, 'core/projects.html')

random_word/views.py
from django.shortcuts import render, HttpResponse
from django.utils.crypto import get_random_string

# Create your views here.

def index(request):
    request.session["random_count"] = 0
    return render(request, 'random_word/index.html')

def random(request):
    word = get_random_string(length=14)
    context = {
        'random_word':word
    }
    request.session["random_count"] += 1
    return render(request, 'random_word/index.html', context)

def reset(request):
    request.session["random_count"] = 0
    #request.session.flush()
    return render(request, 'random_word/index.html')

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-cl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--link bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.css"/>

    <!--CSS base project-->
    <link rel="stylesheet" href="{% static 'core/css/my_styles.css' %}">
    <link rel="icon" type="image/ico" href="{% static 'img/rocket_512x512.png' %}">

    <!--CSS app-->
    {% block css_app %}{% endblock %}

    <!-- JS Jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.js"></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body onload="FechaHora()">  
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:home' %}">
                <img class="img-nav" src="{% static 'core/img/rocket_512x512.png' %}" alt="Rocket">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a>
                    <a class="nav-link" href="#">About</a>
                    <a class="nav-link" href="{% url 'core:projects' %}">Projects</a>
                    <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
                </div>     
                        
            </div>
            <div id='reloj' class="text-white"></div>   
        </div>
    </nav>  

    {% block content %}{% endblock %}

    <footer class="footer mt-4">

    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.js"></script>

    <script src="{% static 'core/js/time.js' %}"></script>
</body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title %}Contáctame!!{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row ">
        <div class="col-md-6">
            <form action="/registro" method="post" class>
                {% csrf_token %}
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">Registro Nuevo Usuario</h2>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" name="email" id="email" placeholder="name@example.com">
                        </div>
                        <div class="mb-3">
                            <label for="nombre" class="form-label">Nombre</label>
                            <input type="text" class="form-control" name="nombre" id="nombre" placeholder="Pepito Los Palotes">
                        </div>
                        <div class="mb-3">
                            <label for="ciudad" class="form-label">Ciudad Natal</label>
                            <input type="text" class="form-control" name="ciudad" id="ciudad" placeholder="Valparaíso">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-secondary"type="submit">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <img class="d-none d-md-block"  src="http://picsum.photos/400/400" alt="">
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
    <div id="carouselIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
            <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
            <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="5" aria-label="Slide 6"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <a href="http://www.google.com">
                    <img src="{% static 'core/img/001-1200x500.jpg' %}" class="d-block w-100" alt="...">
                </a>
            </div>
            <div class="carousel-item">
                <img src="{% static 'core/img/002-1200x500.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'core/img/003-1200x500.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'core/img/004-1200x500.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'core/img/005-1200x500.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'core/img/006-1200x500.jpg' %}" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
{% endblock %}

core/templates/core/projects.html
{% extends "core/base.html"%}

{% block title %}Proyectos{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row text-center">
        <div class="col-sm-6">
            <a href="{% url 'random_word:home' %}" type="button" class="btn btn-secondary">Random Words</a>
        </div>
        <div class="col-sm-6">
            <a href="#" type="button" class="btn btn-secondary">Ninja Gold</a>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/results.html
{% extends "core/base.html" %}

{% block title %}Exito!!!{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        {% if request.session.errores  %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% for error in request.session.errores %}
                <strong>{{error}}</strong><br> 
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead class="table-dark">
                    <tr>
                        <th>Email</th>
                        <th>Nombre</th>
                        <th>Ciudad Natal</th>
                    </tr>
                </thead>
                <tbody>
                    <td>{{request.session.email}}</td>
                    <td>{{request.session.nombre}}</td>
                    <td>{{request.session.ciudad}}</td>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <h3 class="text-primary">Cantidad de personas que se han registrado: {{request.session.contador}}</h3>
    </div>
    
</div>

{% endblock %}

random_word/templates/random_word/index.html
{% extends 'core/base.html' %}

{% load static %}
{% block css_app %}
<link rel="stylesheet" href="{% static 'random_word/css/random_word.css' %}">
{% endblock %}

{% block title %}Random Word{% endblock %}

{% block content %}
<div class="container mt-4 text-center">
    <h3>Random Word (attemp #{{request.session.random_count}})</h3>
    <h1>{{random_word}}</h1>
    <a class="btn btn-secondary m-5" href="{% url 'random_word:random' %}">Generate</a>
    <a class="btn btn-secondary m-5" href="{% url 'random_word:reset' %}">Reset</a>
</div>
{% endblock %}